- hosts: instance3
  become: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
- hosts: instance3
  become: true
  become_method: sudo
  tasks:
    - name: Update the software package repository
      apt:
        name: "*"
        update_cache: yes

    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - openjdk-8-jre-headless
        - git
        - texlive-latex-extra
        - wget
        - deltarpm

    - name: Add Jenkins apt repository key.
      apt_key:
         url: https://pkg.jenkins.io/debian/jenkins.io.key
         state: present

    - name: Add Jenkins apt repository.
      apt_repository:
         repo: deb https://pkg.jenkins.io/debian binary/
         state: present
         update_cache: true

    - name: Install Jenkins
      apt:
        name: "jenkins"
        state: present
        
     - name: Allow port 8080
      shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

    - name: Start the server
      service:
        name: jenkins
        state: started

    - wait_for:
        port: 8080

    - name: If exists
      stat:
        path: /var/lib/jenkins/secrets/initialAdminPassword
      register: st

    - name: Get Admin Password
      become: yes
      become_method: sudo
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      when: st.stat.exists

    - name: Create sonar container
      docker_container:
        name: sonar
        image: sonarqube
        ports: 9000:9000
        state: started

    - wait_for:
        port: 9000
        
     - name: Create artifactory container
      docker_container:
        name: artifactory
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        ports: 8081:8081
        state: started
        env:
            EXTRA_JAVA_OPTIONS: -Xms512m -Xmx2g -Xss256k -XX:+UseG1GC
    - wait_for:
        port: 8081   
